// vue/src/App.vue
<template>
  <form @submit.prevent="onSubmit">
    <div>
      <label>
        氏名
        <input name="name" v-model="name" />
      </label>
    </div>

    <DatePicker :year.sync="year" :month.sync="month" :date.sync="date" />

    <button>送信</button>
  </form>
</template>

<script lang="ts">
import Vue from "vue"
import DatePicker from "./components/DatePicker.vue"

export default Vue.extend({
  name: "App",
  components: { DatePicker },
  data: (): Partial<{
    name: string
    year: number
    month: number
    date: number
  }> => ({
    name: "",
    year: undefined,
    month: undefined,
    date: undefined
  }),
  methods: {
    onSubmit() {
      alert(`Hello, ${name}. ${this.year}/${this.month}/${this.date}`)
    }
  }
})
</script>

// react/src/App.tsx
import React, { useCallback, useState } from "react"
import { DatePicker } from "./components/DatePicker"

function App() {
  const [name, setName] = useState("")
  const [year, setYear] = useState<number | undefined>()
  const [month, setMonth] = useState<number | undefined>()
  const [date, setDate] = useState<number | undefined>()

  const onSubmit = useCallback(
    (e: React.FormEvent<HTMLFormElement>) => {
      e.preventDefault()
      alert(`Hello, ${name}. ${year}/${month}/${date}`)
    },
    [name, year, month, date]
  )

  return (
    <form onSubmit={onSubmit}>
      <input
        name="name"
        value={name}
        onChange={(e) => setName(e.target.value)}
      />
      <DatePicker {...{ year, month, date, setYear, setMonth, setDate }} />
      <button>送信</button>
    </form>
  )
}
export default App
