// svelte/src/App.svelte
<script lang="ts">
  import Form from "./components/Form.svelte"
  import type { TForm } from "./type"

  let forms: Partial<TForm>[] = []
  const getEmptyForm = (): Partial<TForm> => ({})

  function onSubmit() {
    forms.forEach((form) => {
      alert(`${form.name}, ${form.year}, ${form.month}, ${form.date}`)
    })
  }

  function addPerson() {
    forms = [...forms, getEmptyForm()]
  }
</script>

<style>
  form {
    background: orange;
  }
</style>

<button on:click={addPerson}>追加</button>
<form on:submit|preventDefault={onSubmit}>
  {#each forms as form, i}
    <p>{i + 1}</p>
    <Form bind:form />
  {/each}
  <button>送信</button>
</form>

// vue/src/App.vue
<template>
  <form @submit.prevent="onSubmit">
    <div>
      <label>
        氏名
        <input name="name" v-model="name" />
      </label>
    </div>

    <DatePicker :year.sync="year" :month.sync="month" :date.sync="date" />

    <button>送信</button>
  </form>
</template>

<script lang="ts">
import Vue from "vue"
import DatePicker from "./components/DatePicker.vue"

export default Vue.extend({
  name: "App",
  components: { DatePicker },
  data: (): Partial<{
    name: string
    year: number
    month: number
    date: number
  }> => ({
    name: "",
    year: undefined,
    month: undefined,
    date: undefined
  }),
  methods: {
    onSubmit() {
      alert(`Hello, ${name}. ${this.year}/${this.month}/${this.date}`)
    }
  }
})
</script>
